import React, { useEffect, useMemo, useState } from 'react';
import { Link, NavLink, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import {
  Activity, ArrowRight, Bell, BookOpen, BriefcaseBusiness, CalendarDays, CheckCircle2,
  ChevronDown, CircleDollarSign, ClipboardCheck, Command, FileText, FolderLock, HeartPulse,
  LayoutDashboard, Loader2, LockKeyhole, LogOut, Menu, MessageSquare, Plus, Search, Settings,
  ShieldCheck, Sparkles, Target, Users, WalletCards, X, Zap
} from 'lucide-react';
import { useAuth } from '../auth/AuthProvider.jsx';
import { canRoleAccess, moduleDefinitions, navigation, ORG_ADMIN_ROLES, roleHome } from '../lib/iwwConfig.js';
import { requireSupabase } from '../lib/supabase.js';
import {
  createOrganizationRecord, createPersonalRecord, getBilling, getConversationMessages, getDashboardSnapshot,
  getDelegatedMembers, getGovernance, getInbox, getProgrammes, getResources, getTeam, getWealthWorkspace,
  getWellbeingWorkspace, issueInvitation, listOrganizationRecords, listPersonalRecords, sendMessage, updateRecord
} from '../services/iwwData.js';
import './iww-app.css';

const iconById = {
  overview: LayoutDashboard, wellbeing: HeartPulse, wealth: WalletCards, goals: Target, programmes: BookOpen,
  appointments: CalendarDays, messages: MessageSquare, documents: FolderLock, tasks: ClipboardCheck,
  resources: BookOpen, delegated: Users, team: Users, operations: Activity, reports: FileText,
  governance: ShieldCheck, integrations: Zap, billing: CircleDollarSign, settings: Settings,
};

function Loading({ label = 'Loading your IWW workspace…' }) {
  return <main className="iww-full-state"><Loader2 className="iww-spin"/><h1>{label}</h1></main>;
}

function ConfigurationState() {
  return <main className="iww-full-state"><LockKeyhole/><h1>IWW data connection is not configured</h1><p>This deployment needs the dedicated IWW Supabase URL and publishable key. No other project is used as a fallback.</p><Link to="/">Return to public site</Link></main>;
}

function AccessDenied() {
  return <section className="iww-state-panel"><LockKeyhole/><h2>Access not assigned</h2><p>Your IWW role does not permit this module in the selected organization.</p><Link to="/app/overview">Return to overview</Link></section>;
}

function RoleRoute({ roles, children }) {
  const { role } = useAuth();
  return roles.includes(role) ? children : <AccessDenied/>;
}

function CommandPalette({ open, onClose }) {
  const auth = useAuth();
  const navigate = useNavigate();
  const [query, setQuery] = useState('');
  const items = useMemo(() => navigation.filter((item)=>canRoleAccess(auth.role,item)).filter((item)=>`${item.label} ${item.id}`.toLowerCase().includes(query.toLowerCase())), [auth.role, query]);
  useEffect(()=>{ if (!open) setQuery(''); },[open]);
  if (!open) return null;
  return <div className="iww-command-backdrop" role="presentation" onMouseDown={onClose}>
    <div className="iww-command" role="dialog" aria-modal="true" aria-label="IWW command and navigation" onMouseDown={(e)=>e.stopPropagation()}>
      <div className="iww-command-search"><Search size={17}/><input autoFocus placeholder="Find a module" value={query} onChange={(e)=>setQuery(e.target.value)}/><button onClick={onClose} aria-label="Close command menu"><X size={16}/></button></div>
      <div className="iww-command-results">{items.map((item)=><button key={item.id} onClick={()=>{navigate(item.href);onClose();}}><strong>{item.label}</strong><span>{item.href}</span><ArrowRight size={15}/></button>)}{!items.length&&<p>No matching IWW module.</p>}</div>
    </div>
  </div>;
}

function AppShell({ children }) {
  const auth = useAuth();
  const location = useLocation();
  const navigate = useNavigate();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [commandOpen, setCommandOpen] = useState(false);
  const items = navigation.filter((item)=>canRoleAccess(auth.role,item));
  const current = items.find((item)=>location.pathname.startsWith(item.href)) || items[0];
  useEffect(()=>setMobileOpen(false),[location.pathname]);
  useEffect(()=>{
    const handler=(event)=>{ if ((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setCommandOpen(true);} if(event.key==='Escape'){setMobileOpen(false);setCommandOpen(false);} };
    window.addEventListener('keydown',handler); return()=>window.removeEventListener('keydown',handler);
  },[]);

  return <div className="iww-app">
    <a href="#iww-main" className="iww-skip">Skip to content</a>
    {mobileOpen&&<button className="iww-sidebar-scrim" aria-label="Close navigation" onClick={()=>setMobileOpen(false)}/>} 
    <aside className={`iww-sidebar ${mobileOpen?'open':''}`} aria-label="IWW workspace navigation">
      <div className="iww-sidebar-brand"><Link to="/app/overview" className="iww-mark">IW</Link><div><strong>Infinite World</strong><span>of Well-Being</span></div><button className="iww-mobile-close" onClick={()=>setMobileOpen(false)} aria-label="Close navigation"><X size={17}/></button></div>
      <div className="iww-org-card"><span>Organization</span><strong>{auth.organization?.name || 'IWW workspace'}</strong><small>{String(auth.role||'member').replaceAll('_',' ')}</small></div>
      <nav className="iww-nav">{items.map((item)=>{const Icon=iconById[item.id]||Activity;return <NavLink key={item.id} to={item.href} className={({isActive})=>isActive?'active':''}><Icon size={17}/><span>{item.label}</span></NavLink>;})}</nav>
      <div className="iww-sidebar-foot"><Link to="/" target="_self">Public IWW site</Link><button onClick={async()=>{await auth.signOut();navigate('/auth/sign-in',{replace:true});}}><LogOut size={16}/>Sign out</button></div>
    </aside>
    <div className="iww-main-column">
      <header className="iww-topbar">
        <div className="iww-topbar-left"><button className="iww-menu-button" onClick={()=>setMobileOpen(true)} aria-expanded={mobileOpen} aria-label="Open navigation"><Menu size={19}/></button><div><span>Workspace</span><strong>{current?.label || 'IWW'}</strong></div></div>
        <div className="iww-topbar-actions">
          <button className="iww-command-trigger" onClick={()=>setCommandOpen(true)}><Command size={15}/><span>Search IWW</span><kbd>⌘K</kbd></button>
          {auth.memberships.length>1&&<label className="iww-org-switch"><span className="sr-only">Organization</span><select value={auth.activeMembership?.organization_id||''} onChange={(e)=>auth.chooseOrganization(e.target.value)}>{auth.memberships.map((m)=><option key={m.id} value={m.organization_id}>{m.organizations?.name}</option>)}</select><ChevronDown size={14}/></label>}
          <Link to="/app/overview" className="iww-bell" aria-label="Notifications"><Bell size={18}/></Link>
          <div className="iww-avatar" title={auth.profile?.full_name||auth.user?.email}>{(auth.profile?.full_name||auth.user?.email||'I').slice(0,1).toUpperCase()}</div>
        </div>
      </header>
      <main id="iww-main" tabIndex="-1" className="iww-content">{children}</main>
    </div>
    <CommandPalette open={commandOpen} onClose={()=>setCommandOpen(false)}/>
  </div>;
}

function PageHeader({ eyebrow='IWW workspace', title, description, action }) {
  return <header className="iww-page-header"><div><span>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action}</header>;
}

function Stat({ label, value, hint, icon:Icon=Activity }) {
  return <article className="iww-stat"><div className="iww-stat-icon"><Icon size={18}/></div><div><span>{label}</span><strong>{value}</strong><small>{hint}</small></div></article>;
}

function StatusBlock({ error, loading, empty, emptyText='Nothing has been added yet.' }) {
  if (loading) return <div className="iww-inline-state"><Loader2 className="iww-spin" size={18}/>Loading…</div>;
  if (error) return <div className="iww-inline-state error" role="alert">{error}</div>;
  if (empty) return <div className="iww-inline-state">{emptyText}</div>;
  return null;
}

function RecordForm({ definition, onCreate, busy }) {
  const initial = Object.fromEntries(definition.fields.map((field)=>[field.name, field.defaultValue ?? (field.type==='checkbox'?false:'')]));
  const [form, setForm] = useState(initial);
  async function submit(event){event.preventDefault();await onCreate(form);setForm(initial);}
  return <form className="iww-record-form" onSubmit={submit}>{definition.fields.map((field)=><label key={field.name}>{field.label}{field.type==='textarea'?<textarea required={field.required} value={form[field.name]??''} onChange={(e)=>setForm({...form,[field.name]:e.target.value})}/>:field.type==='select'?<select required={field.required} value={form[field.name]??''} onChange={(e)=>setForm({...form,[field.name]:e.target.value})}><option value="">Select</option>{field.options.map((option)=><option key={option} value={option}>{option.replaceAll('_',' ')}</option>)}</select>:field.type==='checkbox'?<input type="checkbox" checked={Boolean(form[field.name])} onChange={(e)=>setForm({...form,[field.name]:e.target.checked})}/>:<input type={field.type||'text'} step={field.type==='number'?'0.01':undefined} required={field.required} value={form[field.name]??''} onChange={(e)=>setForm({...form,[field.name]:e.target.value})}/>}</label>)}<button className="iww-button" disabled={busy}><Plus size={15}/>Add {definition.title.toLowerCase().replace(/s$/,'')}</button></form>;
}

function CollectionPanel({ definition, userScoped=true, allowCreate=true }) {
  const auth=useAuth(); const [rows,setRows]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function load(){if(!auth.organization||!auth.user)return;setLoading(true);setError('');try{setRows(userScoped?await listPersonalRecords(definition.table,{organizationId:auth.organization.id,userId:auth.user.id}):await listOrganizationRecords(definition.table,auth.organization.id));}catch(e){setError(e.message||'Unable to load records.');}finally{setLoading(false);}}
  useEffect(()=>{load();},[auth.organization?.id,auth.user?.id,definition.table,userScoped]);
  async function create(payload){setBusy(true);setError('');try{if(userScoped)await createPersonalRecord(definition.table,payload,{organizationId:auth.organization.id,userId:auth.user.id});else await createOrganizationRecord(definition.table,payload,{organizationId:auth.organization.id,userId:auth.user.id});await load();}catch(e){setError(e.message||'Unable to save.');}finally{setBusy(false);}}
  return <section className="iww-panel"><div className="iww-panel-head"><div><h2>{definition.title}</h2><p>{definition.description}</p></div><span className="iww-count">{rows.length}</span></div>{allowCreate&&<RecordForm definition={definition} onCreate={create} busy={busy}/>}<StatusBlock loading={loading} error={error} empty={!loading&&!error&&!rows.length}/>{rows.length>0&&<div className="iww-record-list">{rows.map((row)=><article key={row.id}><div><strong>{row.title||row.name||row.appointment_type||row.status||'Record'}</strong><span>{row.category||row.asset_type||row.liability_type||row.frequency||row.status||new Date(row.created_at).toLocaleDateString()}</span></div>{row.status&&<small className="iww-status">{String(row.status).replaceAll('_',' ')}</small>}</article>)}</div>}</section>;
}

function OverviewPage(){const auth=useAuth();const[data,setData]=useState(null);const[error,setError]=useState('');useEffect(()=>{if(!auth.organization||!auth.user)return;getDashboardSnapshot({organizationId:auth.organization.id,userId:auth.user.id}).then(setData).catch(e=>setError(e.message));},[auth.organization?.id,auth.user?.id]);return <><PageHeader title={`Welcome${auth.profile?.full_name?`, ${auth.profile.full_name.split(' ')[0]}`:''}`} description="Your calm operational view across wellbeing, wealth planning, appointments and action items."/><StatusBlock loading={!data&&!error} error={error}/>{data&&<><section className="iww-stat-grid"><Stat label="Active goals" value={data.counts.goals} hint="personal priorities" icon={Target}/><Stat label="Habits" value={data.counts.habits} hint="active routines" icon={CheckCircle2}/><Stat label="Appointments" value={data.counts.appointments} hint="upcoming" icon={CalendarDays}/><Stat label="Open tasks" value={data.counts.tasks} hint="organization-visible under your role" icon={ClipboardCheck}/></section><section className="iww-two-col"><article className="iww-panel"><div className="iww-panel-head"><div><h2>Next appointments</h2><p>Upcoming confirmed and requested sessions.</p></div></div>{data.appointments.length?data.appointments.map(a=><div className="iww-feed-row" key={a.id}><CalendarDays size={16}/><div><strong>{a.title}</strong><span>{new Date(a.starts_at).toLocaleString()}</span></div><small>{a.status}</small></div>):<div className="iww-inline-state">No upcoming appointment.</div>}</article><article className="iww-panel"><div className="iww-panel-head"><div><h2>Notifications</h2><p>Role-safe account and programme updates.</p></div></div>{data.notifications.length?data.notifications.map(n=><div className="iww-feed-row" key={n.id}><Bell size={16}/><div><strong>{n.title}</strong><span>{n.body}</span></div></div>):<div className="iww-inline-state">You are all caught up.</div>}</article></section></>}</>}

function WellbeingPage(){const auth=useAuth();const[data,setData]=useState(null);const[error,setError]=useState('');const[checkin,setCheckin]=useState({mood_score:5,energy_score:5,reflection:''});const[busy,setBusy]=useState(false);async function load(){try{setData(await getWellbeingWorkspace({organizationId:auth.organization.id,userId:auth.user.id}));}catch(e){setError(e.message)}}useEffect(()=>{if(auth.organization&&auth.user)load();},[auth.organization?.id,auth.user?.id]);async function saveCheckin(e){e.preventDefault();setBusy(true);try{await createPersonalRecord('wellbeing_checkins',checkin,{organizationId:auth.organization.id,userId:auth.user.id});setCheckin({mood_score:5,energy_score:5,reflection:''});await load();}catch(e){setError(e.message)}finally{setBusy(false)}}return <><PageHeader title="Wellbeing workspace" description="User-managed plans, check-ins, coaching and programme progress. This supports reflection and coaching; it does not diagnose or treat medical conditions."/><StatusBlock loading={!data&&!error} error={error}/>{data&&<><section className="iww-stat-grid"><Stat label="Plans" value={data.plans.length} hint="wellbeing plans" icon={HeartPulse}/><Stat label="Check-ins" value={data.checkins.length} hint="recorded reflections" icon={Activity}/><Stat label="Habits" value={data.habits.length} hint="tracked practices" icon={CheckCircle2}/><Stat label="Assessments" value={data.assessments.length} hint="self-assessments" icon={ClipboardCheck}/></section><section className="iww-two-col"><article className="iww-panel"><div className="iww-panel-head"><div><h2>New check-in</h2><p>Record how the day feels without clinical interpretation.</p></div></div><form className="iww-record-form" onSubmit={saveCheckin}><label>Mood (1–10)<input type="number" min="1" max="10" value={checkin.mood_score} onChange={e=>setCheckin({...checkin,mood_score:Number(e.target.value)})}/></label><label>Energy (1–10)<input type="number" min="1" max="10" value={checkin.energy_score} onChange={e=>setCheckin({...checkin,energy_score:Number(e.target.value)})}/></label><label className="wide">Reflection<textarea value={checkin.reflection} onChange={e=>setCheckin({...checkin,reflection:e.target.value})}/></label><button className="iww-button" disabled={busy}>Save check-in</button></form></article><article className="iww-panel"><div className="iww-panel-head"><div><h2>Recent check-ins</h2><p>Your latest self-recorded reflections.</p></div></div>{data.checkins.slice(0,6).map(c=><div key={c.id} className="iww-feed-row"><HeartPulse size={16}/><div><strong>Mood {c.mood_score}/10 · Energy {c.energy_score}/10</strong><span>{c.reflection||'No written reflection.'}</span></div><small>{new Date(c.created_at).toLocaleDateString()}</small></div>)}{!data.checkins.length&&<div className="iww-inline-state">No check-ins yet.</div>}</article></section>}</>}

function WealthPage(){const auth=useAuth();const[data,setData]=useState(null);const[error,setError]=useState('');useEffect(()=>{if(auth.organization&&auth.user)getWealthWorkspace({organizationId:auth.organization.id,userId:auth.user.id}).then(setData).catch(e=>setError(e.message));},[auth.organization?.id,auth.user?.id]);const assetTotal=data?.assets.reduce((s,a)=>s+Number(a.estimated_value||0),0)||0;const debtTotal=data?.liabilities.reduce((s,a)=>s+Number(a.balance||0),0)||0;return <><PageHeader title="Wealth planning" description="User-entered planning, tracking, education and adviser-supported review. IWW does not execute trades, move money, or make autonomous investment decisions."/><StatusBlock loading={!data&&!error} error={error}/>{data&&<><section className="iww-stat-grid"><Stat label="Planning assets" value={assetTotal.toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:0})} hint="user-entered estimates" icon={WalletCards}/><Stat label="Liabilities" value={debtTotal.toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:0})} hint="user-entered balances" icon={CircleDollarSign}/><Stat label="Wealth goals" value={data.goals.length} hint="planning goals" icon={Target}/><Stat label="Reviews" value={data.reviews.length} hint="recorded review cycles" icon={ClipboardCheck}/></section><section className="iww-two-col"><CollectionPanel definition={moduleDefinitions.assets}/><CollectionPanel definition={moduleDefinitions.liabilities}/></section></>}</>}

function GoalsPage(){return <><PageHeader title="Goals & habits" description="Turn plans into small, measurable actions."/><section className="iww-two-col"><CollectionPanel definition={moduleDefinitions.goals}/><CollectionPanel definition={moduleDefinitions.habits}/></section></>}
function AppointmentsPage(){return <><PageHeader title="Appointments" description="Request and track advisor, coaching and wellbeing sessions."/><CollectionPanel definition={moduleDefinitions.appointments}/></>}
function TasksPage(){return <><PageHeader title="Tasks" description="Role-safe operational work and follow-up."/><CollectionPanel definition={moduleDefinitions.tasks} userScoped={false}/></>}

function ProgrammesPage(){const auth=useAuth();const[rows,setRows]=useState([]);const[message,setMessage]=useState('');const[error,setError]=useState('');useEffect(()=>{if(auth.organization)getProgrammes(auth.organization.id).then(setRows).catch(e=>setError(e.message));},[auth.organization?.id]);async function enrol(programmeId){setMessage('');try{await createPersonalRecord('programme_enrolments',{programme_id:programmeId,status:'enrolled',enrolled_at:new Date().toISOString()},{organizationId:auth.organization.id,userId:auth.user.id});setMessage('Programme enrolment recorded.');}catch(e){setMessage(e.message)}}return <><PageHeader title="Programmes" description="Structured education, coaching and wellbeing programmes published by your IWW organization."/><StatusBlock error={error} empty={!rows.length} emptyText="No programmes are currently published."/>{message&&<p className="iww-notice">{message}</p>}<section className="iww-card-grid">{rows.map(p=><article className="iww-module-card" key={p.id}><span>{p.category||'programme'}</span><h2>{p.name}</h2><p>{p.description||'Programme details will appear here.'}</p><button className="iww-button secondary" onClick={()=>enrol(p.id)}>Enrol <ArrowRight size={14}/></button></article>)}</section></>}

function ResourcesPage(){const auth=useAuth();const[rows,setRows]=useState([]);const[error,setError]=useState('');useEffect(()=>{if(auth.organization)getResources(auth.organization.id).then(setRows).catch(e=>setError(e.message));},[auth.organization?.id]);return <><PageHeader title="Resource library" description="Organization-approved education and wellbeing resources."/><StatusBlock error={error} empty={!rows.length} emptyText="No resources are currently published."/><section className="iww-card-grid">{rows.map(r=><article className="iww-module-card" key={r.id}><span>{r.resource_type||'resource'}</span><h2>{r.title}</h2><p>{r.summary||r.description}</p>{r.url&&<a href={r.url} target="_blank" rel="noreferrer">Open resource <ArrowRight size={14}/></a>}</article>)}</section></>}

function DocumentsPage(){const auth=useAuth();const[rows,setRows]=useState([]);const[file,setFile]=useState(null);const[error,setError]=useState('');const[busy,setBusy]=useState(false);async function load(){try{setRows(await listPersonalRecords('documents',{organizationId:auth.organization.id,userId:auth.user.id}));}catch(e){setError(e.message)}}useEffect(()=>{if(auth.organization&&auth.user)load();},[auth.organization?.id,auth.user?.id]);async function upload(e){e.preventDefault();if(!file)return;setBusy(true);setError('');try{const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=`${auth.organization.id}/${auth.user.id}/${crypto.randomUUID()}-${safe}`;const client=requireSupabase();const{error:upErr}=await client.storage.from('iww-documents').upload(path,file,{upsert:false,contentType:file.type});if(upErr)throw upErr;await createPersonalRecord('documents',{title:file.name,storage_path:path,mime_type:file.type,size_bytes:file.size,document_type:'member_upload'},{organizationId:auth.organization.id,userId:auth.user.id});setFile(null);await load();}catch(e){setError(e.message)}finally{setBusy(false)}}return <><PageHeader title="Document vault" description="Private IWW document metadata and storage protected by organization and member access policies."/><section className="iww-panel"><form className="iww-upload" onSubmit={upload}><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)} aria-label="Choose document"/><button className="iww-button" disabled={busy||!file}>Upload</button></form><StatusBlock error={error} empty={!rows.length} emptyText="No documents uploaded yet."/>{rows.map(d=><div className="iww-feed-row" key={d.id}><FileText size={16}/><div><strong>{d.title}</strong><span>{d.document_type} · {d.mime_type||'file'}</span></div><small>{new Date(d.created_at).toLocaleDateString()}</small></div>)}</section></>}

function MessagesPage(){const auth=useAuth();const[inbox,setInbox]=useState([]);const[selected,setSelected]=useState(null);const[messages,setMessages]=useState([]);const[body,setBody]=useState('');const[error,setError]=useState('');async function loadInbox(){try{const data=await getInbox(auth.organization.id);setInbox(data);if(!selected&&data[0])setSelected(data[0]);}catch(e){setError(e.message)}}useEffect(()=>{if(auth.organization)loadInbox();},[auth.organization?.id]);useEffect(()=>{if(selected)getConversationMessages({organizationId:auth.organization.id,conversationId:selected.conversation_id||selected.id}).then(setMessages).catch(e=>setError(e.message));},[selected?.conversation_id,selected?.id,auth.organization?.id]);async function submit(e){e.preventDefault();if(!body.trim()||!selected)return;try{await sendMessage({organizationId:auth.organization.id,conversationId:selected.conversation_id||selected.id,userId:auth.user.id,body});setBody('');setMessages(await getConversationMessages({organizationId:auth.organization.id,conversationId:selected.conversation_id||selected.id}));}catch(e){setError(e.message)}}return <><PageHeader title="Messages" description="Secure, participant-authorized member, advisor and practitioner conversations."/><StatusBlock error={error}/><section className="iww-messages"><aside>{inbox.map(c=><button className={selected&&(c.conversation_id||c.id)===(selected.conversation_id||selected.id)?'active':''} key={c.conversation_id||c.id} onClick={()=>setSelected(c)}><strong>{c.title||'Conversation'}</strong><span>{c.last_message||'Open conversation'}</span></button>)}{!inbox.length&&<p>No conversations yet.</p>}</aside><article>{selected?<><div className="iww-message-thread">{messages.map(m=><div key={m.id} className={m.sender_user_id===auth.user.id?'mine':''}><span>{m.body}</span><small>{new Date(m.created_at).toLocaleString()}</small></div>)}</div><form onSubmit={submit} className="iww-message-compose"><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Write a message" required/><button className="iww-button">Send</button></form></>:<div className="iww-inline-state">Choose a conversation.</div>}</article></section></>}

function TeamPage(){const auth=useAuth();const[team,setTeam]=useState([]);const[form,setForm]=useState({email:'',role:'member'});const[token,setToken]=useState('');const[error,setError]=useState('');async function load(){try{setTeam(await getTeam(auth.organization.id));}catch(e){setError(e.message)}}useEffect(()=>{if(auth.organization)load();},[auth.organization?.id]);async function invite(e){e.preventDefault();setToken('');setError('');try{const result=await issueInvitation({organizationId:auth.organization.id,email:form.email,role:form.role,userId:auth.user.id});setToken(typeof result==='string'?result:result?.token||JSON.stringify(result));setForm({email:'',role:'member'});}catch(e){setError(e.message)}}return <><PageHeader title="Team & access" description="Invite people, assign IWW roles and review active organization membership."/><section className="iww-two-col"><article className="iww-panel"><div className="iww-panel-head"><div><h2>Active team</h2><p>{team.length} active membership records</p></div></div><StatusBlock error={error} empty={!team.length}/>{team.map(m=><div className="iww-feed-row" key={m.id}><Users size={16}/><div><strong>{m.profiles?.full_name||m.user_id}</strong><span>{m.role.replaceAll('_',' ')}</span></div><small>{m.status}</small></div>)}</article><article className="iww-panel"><div className="iww-panel-head"><div><h2>Issue invitation</h2><p>One-time token is returned once. Deliver it through an approved channel.</p></div></div><form className="iww-record-form" onSubmit={invite}><label>Email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{['admin','operations_manager','advisor','practitioner','member','family_delegate'].map(r=><option key={r} value={r}>{r.replaceAll('_',' ')}</option>)}</select></label><button className="iww-button">Create invitation</button></form>{token&&<div className="iww-secret-once"><strong>One-time invitation token</strong><code>{token}</code><small>Copy it now. The database stores only a hash.</small></div>}</article></section></>}

function OperationsPage(){const auth=useAuth();const[tasks,setTasks]=useState([]);const[appointments,setAppointments]=useState([]);const[approvals,setApprovals]=useState([]);const[error,setError]=useState('');useEffect(()=>{if(!auth.organization)return;Promise.all([listOrganizationRecords('tasks',auth.organization.id),listOrganizationRecords('appointments',auth.organization.id),listOrganizationRecords('workflow_approvals',auth.organization.id)]).then(([a,b,c])=>{setTasks(a);setAppointments(b);setApprovals(c)}).catch(e=>setError(e.message));},[auth.organization?.id]);return <><PageHeader title="Operations" description="Queues, tasks, appointments and approvals visible only to authorized operational roles."/><StatusBlock error={error}/><section className="iww-stat-grid"><Stat label="Open tasks" value={tasks.filter(t=>t.status!=='completed').length} hint="operational queue" icon={ClipboardCheck}/><Stat label="Appointments" value={appointments.filter(a=>a.status!=='cancelled').length} hint="active records" icon={CalendarDays}/><Stat label="Pending approvals" value={approvals.filter(a=>a.status==='pending').length} hint="governed actions" icon={ShieldCheck}/><Stat label="Role" value={auth.role.replaceAll('_',' ')} hint="server-authoritative membership" icon={Users}/></section><CollectionPanel definition={moduleDefinitions.tasks} userScoped={false}/></>}

function ReportsPage(){const auth=useAuth();const[rows,setRows]=useState([]);const[error,setError]=useState('');useEffect(()=>{if(auth.organization)listOrganizationRecords('reports',auth.organization.id).then(setRows).catch(e=>setError(e.message));},[auth.organization?.id]);return <><PageHeader title="Reports" description="Saved report definitions and role-safe operational reporting."/><StatusBlock error={error} empty={!rows.length} emptyText="No reports have been created yet."/>{rows.map(r=><article className="iww-panel" key={r.id}><h2>{r.name}</h2><p>{r.description}</p><small>{r.report_type}</small></article>)}</>}

function GovernancePage(){const auth=useAuth();const[data,setData]=useState(null);const[error,setError]=useState('');useEffect(()=>{if(auth.organization)getGovernance(auth.organization.id).then(setData).catch(e=>setError(e.message));},[auth.organization?.id]);return <><PageHeader title="Governance & privacy" description="Consent, policy acknowledgement, approvals, integration state and immutable audit evidence."/><StatusBlock loading={!data&&!error} error={error}/>{data&&<section className="iww-two-col"><article className="iww-panel"><div className="iww-panel-head"><div><h2>Audit events</h2><p>Append-only governance history.</p></div></div>{data.audit.slice(0,30).map(a=><div className="iww-feed-row" key={a.id}><ShieldCheck size={16}/><div><strong>{a.action}</strong><span>{a.target_type}{a.target_id?` · ${a.target_id}`:''}</span></div><small>{new Date(a.created_at).toLocaleString()}</small></div>)}</article><article className="iww-panel"><div className="iww-panel-head"><div><h2>Control summary</h2><p>Current evidence records.</p></div></div><div className="iww-governance-counts"><Stat label="Consents" value={data.consents.length}/><Stat label="Policy acknowledgements" value={data.policies.length}/><Stat label="Approvals" value={data.approvals.length}/><Stat label="Integrations" value={data.integrations.length}/></div></article></section>}</>}

async function callIwwApi(resource, body, session){const response=await fetch(`/api/iww?resource=${encodeURIComponent(resource)}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(body)});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'IWW server operation failed.');return result;}

function IntegrationsPage(){const auth=useAuth();const[rows,setRows]=useState([]);const[message,setMessage]=useState('');const[error,setError]=useState('');async function load(){try{setRows(await listOrganizationRecords('integration_connections',auth.organization.id));}catch(e){setError(e.message)}}useEffect(()=>{if(auth.organization)load();},[auth.organization?.id]);async function action(provider,operation){setMessage('');setError('');try{const result=await callIwwApi('integration',{organizationId:auth.organization.id,provider,operation},auth.session);setMessage(result.message||`${provider} ${operation} completed.`);await load();}catch(e){setError(e.message)}}const providers=['hubspot','google_calendar','stripe'];return <><PageHeader title="Integrations" description="Opt-in, revocable organization connections. Provider tokens remain server-side and never enter Vite browser variables."/><StatusBlock error={error}/>{message&&<p className="iww-notice">{message}</p>}<section className="iww-card-grid">{providers.map(provider=>{const row=rows.find(r=>r.provider===provider);return <article className="iww-module-card" key={provider}><span>{row?.status||'not connected'}</span><h2>{provider.replaceAll('_',' ')}</h2><p>{row?.status==='connected'?'Connection metadata is recorded for this organization.':'Connection requires organization authorization and configured server-side provider credentials.'}</p><div className="iww-actions"><button className="iww-button secondary" onClick={()=>action(provider,'connect')}>Connect / verify</button>{row?.status==='connected'&&<button className="iww-text-button" onClick={()=>action(provider,'revoke')}>Revoke</button>}</div></article>})}</section></>}

function BillingPage(){const auth=useAuth();const[data,setData]=useState(null);const[error,setError]=useState('');const[busy,setBusy]=useState(false);useEffect(()=>{if(auth.organization)getBilling(auth.organization.id).then(setData).catch(e=>setError(e.message));},[auth.organization?.id]);async function portal(){setBusy(true);setError('');try{const result=await callIwwApi('billing-portal',{organizationId:auth.organization.id},auth.session);if(result.url)window.location.assign(result.url);else throw new Error(result.message||'Billing portal is not configured.');}catch(e){setError(e.message)}finally{setBusy(false)}}return <><PageHeader title="Billing & subscription" description="Reference-only billing visibility. Payment secrets and provider actions remain server-side." action={<button className="iww-button" onClick={portal} disabled={busy}>Open billing portal</button>}/><StatusBlock loading={!data&&!error} error={error}/>{data&&<section className="iww-two-col"><article className="iww-panel"><h2>Subscriptions</h2>{data.subscriptions.length?data.subscriptions.map(s=><div className="iww-feed-row" key={s.id}><CircleDollarSign size={16}/><div><strong>{s.plan_name||s.provider}</strong><span>{s.status}</span></div><small>{s.current_period_end?new Date(s.current_period_end).toLocaleDateString():''}</small></div>):<div className="iww-inline-state">No subscription record.</div>}</article><article className="iww-panel"><h2>Billing history</h2>{data.billing.length?data.billing.map(b=><div className="iww-feed-row" key={b.id}><FileText size={16}/><div><strong>{b.description||b.record_type}</strong><span>{b.amount?Number(b.amount).toLocaleString(undefined,{style:'currency',currency:b.currency||'USD'}):b.status}</span></div></div>):<div className="iww-inline-state">No billing records.</div>}</article></section>}</>}

function DelegatedPage(){const auth=useAuth();const[rows,setRows]=useState([]);const[error,setError]=useState('');useEffect(()=>{if(auth.organization)getDelegatedMembers(auth.organization.id).then(setRows).catch(e=>setError(e.message));},[auth.organization?.id]);return <><PageHeader title="Delegated access" description="Only explicitly delegated member records are available here. Organization-wide visibility is never granted to family delegates."/><StatusBlock error={error} empty={!rows.length} emptyText="No active member delegation is assigned to this account."/>{rows.map(r=><article className="iww-panel" key={r.member_user_id}><h2>{r.full_name||'IWW member'}</h2><p>{r.scope_summary||'Limited delegated visibility.'}</p></article>)}</>}

function SettingsPage(){const auth=useAuth();const[form,setForm]=useState({full_name:'',timezone:'UTC'});const[message,setMessage]=useState('');const[error,setError]=useState('');useEffect(()=>{if(auth.profile)setForm({full_name:auth.profile.full_name||'',timezone:auth.profile.timezone||'UTC'});},[auth.profile]);async function save(e){e.preventDefault();setMessage('');setError('');try{const{error:profileError}=await requireSupabase().from('profiles').update(form).eq('user_id',auth.user.id);if(profileError)throw profileError;setMessage('Profile updated.');await auth.refreshContext();}catch(e){setError(e.message)}}return <><PageHeader title="Account & preferences" description="Manage your IWW profile and communication preferences."/><section className="iww-panel"><form className="iww-record-form" onSubmit={save}><label>Full name<input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>Timezone<input value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}/></label><button className="iww-button">Save settings</button></form>{message&&<p className="iww-notice">{message}</p>}{error&&<p className="iww-inline-state error">{error}</p>}</section></>}

function ProtectedApp(){const auth=useAuth();if(!auth.configured)return <ConfigurationState/>;if(auth.loading||auth.contextLoading)return <Loading/>;if(!auth.user)return <Navigate to="/auth/sign-in" state={{from:window.location.pathname}} replace/>;if(!auth.activeMembership)return <Navigate to="/auth/onboarding" replace/>;return <AppShell><Routes><Route path="/app" element={<Navigate to={roleHome[auth.role]||'/app/overview'} replace/>}/><Route path="/app/overview" element={<OverviewPage/>}/><Route path="/app/wellbeing" element={<WellbeingPage/>}/><Route path="/app/wealth" element={<WealthPage/>}/><Route path="/app/goals" element={<GoalsPage/>}/><Route path="/app/programmes" element={<ProgrammesPage/>}/><Route path="/app/appointments" element={<AppointmentsPage/>}/><Route path="/app/messages" element={<MessagesPage/>}/><Route path="/app/documents" element={<DocumentsPage/>}/><Route path="/app/tasks" element={<TasksPage/>}/><Route path="/app/resources" element={<ResourcesPage/>}/><Route path="/app/delegated" element={<RoleRoute roles={['family_delegate']}><DelegatedPage/></RoleRoute>}/><Route path="/app/team" element={<RoleRoute roles={['owner','admin']}><TeamPage/></RoleRoute>}/><Route path="/app/operations" element={<RoleRoute roles={['owner','admin','operations_manager']}><OperationsPage/></RoleRoute>}/><Route path="/app/reports" element={<RoleRoute roles={['owner','admin','operations_manager','advisor','practitioner']}><ReportsPage/></RoleRoute>}/><Route path="/app/governance" element={<RoleRoute roles={['owner','admin']}><GovernancePage/></RoleRoute>}/><Route path="/app/integrations" element={<RoleRoute roles={['owner','admin']}><IntegrationsPage/></RoleRoute>}/><Route path="/app/billing" element={<RoleRoute roles={['owner','admin','member']}><BillingPage/></RoleRoute>}/><Route path="/app/settings" element={<SettingsPage/>}/><Route path="*" element={<Navigate to="/app/overview" replace/>}/></Routes></AppShell>}

export function IwwSaaSApp(){return <ProtectedApp/>;}
