import { useCallback, useEffect, useState } from 'react';
import { Activity, ArrowRight, Building2, Boxes, LogOut, RefreshCcw, ShieldCheck, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../auth/AuthContext';
import { requireSupabase } from '../lib/supabase';

export default function PlatformPage() {
  const auth = useAuth();
  const [state,setState]=useState({loading:true,error:'',organizations:[],catalogCount:0});
  const load=useCallback(async()=>{setState(current=>({...current,loading:true,error:''}));try{const client=requireSupabase();const [{data:organizations,error:organizationError},{count,error:catalogError}]=await Promise.all([client.rpc('platform_organization_summary'),client.from('integration_catalog').select('id',{count:'exact',head:true}).eq('status','active')]);if(organizationError)throw organizationError;if(catalogError)throw catalogError;setState({loading:false,error:'',organizations:organizations||[],catalogCount:count||0});}catch(error){setState({loading:false,error:error.message,organizations:[],catalogCount:0});}},[]);
  useEffect(()=>{load();},[load]);
  const activeOrganizations=state.organizations.filter(item=>item.status==='active').length;
  const seats=state.organizations.reduce((sum,item)=>sum+Number(item.active_members||0),0);
  return <main className="platform-page"><aside><div className="platform-brand"><span>IW</span><div><strong>IWW Platform</strong><small>Administration</small></div></div><nav><a className="active" href="#overview"><Activity/>Overview</a><a href="#organizations"><Building2/>Organizations</a><a href="#catalog"><Boxes/>Integration catalog</a><a href="#governance"><ShieldCheck/>Governance</a></nav><div><Link to="/workspaces">Client workspaces</Link><button onClick={auth.signOut}><LogOut/>Sign out</button></div></aside><section><header><div><span>INTERNAL PLATFORM PLANE</span><h1>Infinite World operations</h1><p>Service-level administration without automatic access to client wellbeing, wealth, messages or documents.</p></div><span className="platform-role"><ShieldCheck/>{auth.platformStaff.role.replaceAll('_',' ')}</span></header>{state.error&&<div className="form-alert error">{state.error}<button onClick={load}><RefreshCcw/></button></div>}<div className="metric-grid platform-metrics"><article className="metric-card"><Building2/><span>Active organizations</span><strong>{state.loading?'—':activeOrganizations}</strong></article><article className="metric-card"><Users/><span>Authorized seats</span><strong>{state.loading?'—':seats}</strong></article><article className="metric-card"><Boxes/><span>Integration catalog</span><strong>{state.loading?'—':state.catalogCount}</strong></article></div><div className="platform-panel" id="organizations"><div className="panel-heading"><div><span>ORGANIZATIONS</span><h2>Tenant service directory</h2></div></div>{state.loading?<div className="app-state app-loading"><span className="spinner"/></div>:<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Organization</th><th>Status</th><th>Seats</th><th>Created</th></tr></thead><tbody>{state.organizations.map(item=><tr key={item.organization_id}><td><strong>{item.name}</strong><small>{item.slug}</small></td><td><span className={`status-pill ${item.status}`}>{item.status}</span></td><td>{item.active_members}</td><td>{new Date(item.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>}</div><div className="platform-panel" id="catalog"><div className="panel-heading"><div><span>CATALOG</span><h2>Organization integration marketplace</h2></div></div><p className="platform-copy">The shared catalog contains {state.catalogCount || 300}+ applications. Client owners authorize connections inside their own workspace; credentials remain server-side and organization-scoped.</p><Link className="app-button secondary" to="/workspaces">Open a client workspace <ArrowRight/></Link></div></section></main>;
}
